height = 64
width = 64
num_channels = 1
pre_seq = 10
after_seq = 10
pre_seq_length = 10
after_seq_length = 10
patch_size = 4
dim = 128
heads = 4
dim_head = 32
dropout = 0.1
attn_dropout = 0.1
drop_path = 0.1
scale_dim = 2
depth = 2
Ndepth = 2
use_physics = True
physics_alpha = 0.1
use_fno = (2, 3)
in_shape = [pre_seq, num_channels, height, width]