height       = 32
width        = 32
num_channels = 2
pre_seq      = 4
after_seq    = 4
patch_size   = 4
dim          = 256
heads        = 8
dim_head     = 32
dropout      = 0.1
attn_dropout = 0.1
drop_path    = 0.25
scale_dim    = 4
depth        = 2
Ndepth       = 2
use_physics  = True
physics_alpha = 0.05
use_fno = (3, 5)
